# # Travis CI build configuration config file.

# Not using Python code, it's just a bone for Travis CI
language: python
python: 3.4

env:
  global:
    - |
      DISPLAY=:0.0
      WINEDLLOVERRIDES="mscoree,mshtml="
      PATH=${PATH//:\.\/node_modules\/\.bin/}    # Workaround for Travis issue #4862
      CWD="$TRAVIS_BUILD_DIR"
  matrix:
    - PLATFORM=MT4

addons:
  hosts:
    - travis.local
  apt:
    packages:
    - xvfb      # X virtual framebuffer.
    - xdotool   # Fake keyboard/mouse input.
    - winbind   # Required for wine.
    - wine
    - tree
    - pv

before_install:
  - set -e

install:
  - set -e

before_script:
  - Xvfb $DISPLAY -screen 0 1024x768x16 &

script:
  - $CWD/scripts/install_mt4.sh
  - $CWD/scripts/dl_bt_data.sh
